

#spring.application.name=TimeTable-generator
#
#spring.datasource.url=jdbc:mysql://localhost:3306/schedulify
#spring.datasource.username=root
#spring.datasource.password=mySQL@0000
#
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
#server.port=${PORT:8080}
#
## Timefold
#
#timefold.solver.termination.spent-limit=10s
#
#logging.level.ai.timefold.solver.core.impl.score=DEBUG
##logging.level.ai.timefold=DEBUG
#
## JWT
#jwt.secret=9f5c3b2d8e7a1f6b4c9d0e8f7a6b5c4d3e2f1a9b8c7d6e5f4a3b2c1d0e9f8a7
#jwt.expiration=86400000
#
#
#
