spring.application.name=TimeTable-generator

spring.datasource.url=jdbc:mysql://${MYSQL_PUBLIC_HOST}:${MYSQL_PUBLIC_PORT}/${MYSQL_DATABASE}?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}

timefold.solver.termination.spent-limit=10s

logging.level.ai.timefold.solver.core.impl.score=DEBUG

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

